"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
editor = "nvim"
diff-formatter = ":git"
default-command = ["log", "-n", "10"]
# diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]

[ui.movement]
edit = true

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }

[aliases]
# Aliases to show other log variants
mlog = ["log", "-r", "more_log()"]
rlog = ["log", "-r", "remote_log()"]
tlog = ["log", "-r", "trunk_log()"]
hlog = ["log", "-r", "my_heads_log()"]
hist = ["log", "-r", "branch_history(@)"]
alog = ["log", "-r", "all()"]

# Show summary of commit without all the changes
view = ["show", "--no-patch"]

[template-aliases]
# Relative timestamp rendered as "x days/hours/seconds ago"
'format_timestamp(timestamp)' = 'timestamp.ago()'

# Display shorter id
'format_short_id(id)' = 'id.shortest(4)'

# Only show name of the author
'format_short_signature(signature)' = 'signature.name()'

# Customize the alias used in log command to show information compactly, and -
# 1. Highlight anonymous commit with changes
'format_short_commit_header(commit)' = """
separate(" ",
  format_short_change_id_with_hidden_and_divergent_info(commit) ++ "/" ++
  format_short_commit_id(commit.commit_id()),
  "(" ++ format_timestamp(commit_timestamp(commit)) ++ ")",
  if(current_working_copy && (!description) && (!commit.empty()), "(DIRTY)"),
  commit.bookmarks(),
  commit.tags(),
  commit.working_copies(),
  if(commit.conflict(), label("conflict", "confict")),
  if(config("ui.show-cryptographic-signatures").as_boolean(),
    "{" ++ format_short_cryptographic_signature(commit.signature()) ++ "}"),
  "[" ++ format_short_signature(commit.author()) ++ "]",
)
"""

[revset-aliases]
# Customize the set of immutable_heads,, in addition to built-in ones
# Any changes NOT made by current user are immutable
# Remote bookmarks (all non-local changes) are considered immutable to avoid accidentally
#   overwriting them.
# Note that local only bookmarks are NOT considered immutable, only remote bookmarks are.
"immutable_heads()" = """
builtin_immutable_heads() | (trunk()..remote_bookmarks()) | (trunk().. & ~mine())
"""

# All visible heads by current author, including from remote
"my_heads()" = "(visible_heads() | remote_bookmarks() ) & mine()"

"_add_log_context(x)" = "ancestors(present(x), 2)"
# The following changes will be shown by default for the `log` command
# 1. Tips of remote bookmarks
# 2. All local bookmarks, the latest tag, the tip of trunk,
#   commits by current author and working copy
# For all the above we add one more commit for context.
"default_log_()" = """
  tracked_remote_bookmarks() |
  bookmarks()|latest(tags(), 1)|trunk()|@|
  (trunk()..my_heads())
"""

"default_log()" = "_add_log_context(default_log_())"

# Intended to show everything which might be relevant because it after the trunk change
"more_log_()" = """
  default_log_() | (trunk()::)
"""

"more_log()" = "_add_log_context(more_log_())"

# Intended to show every possible remote commit, except those in trunk
"remote_log_()" = """
  more_log_() | ((trunk()..remote_bookmarks())::)
"""

"remote_log()" = "_add_log_context(remote_log_())"

# Linear history of the branch
"branch_history(x)" = "..x"

# History of changes in trunk
"trunk_log()" = "branch_history(trunk())"

# All of my_heads() with some context
"my_heads_log()" = "_add_log_context(my_heads())"

[revsets]
log='default_log()'

[templates]
# Show additional stats for the commit first
show = 'builtin_log_detailed ++ diff.summary() ++ "\n" ++ diff.stat() ++ "\n"'

