#!/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

set -x
brew update
brew upgrade
brew bundle --file="${SCRIPT_DIR}/Brewfile"
brew bundle cleanup --force --file="${SCRIPT_DIR}/Brewfile"
