#!/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if command -v apt > /dev/null 2>&1; then
  sudo apt update && sudo apt --yes upgrade && sudo apt --yes autoremove
fi

${SCRIPT_DIR}/sync-brew
